name 'example42-squid'
version '0.0.10'

author 'Sebastian Quaino'
author 'Javier Bertoli'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-squid'
summary 'Puppet module for squid'
description 'This module installs and manages squid. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
